# Generated by Django 4.2.7 on 2026-06-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_role_userprofile_seed_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('mechanic', 'Mechanic'), ('client', 'Client')], default='client', max_length=30),
        ),
    ]
